//SIGN UP


export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const SET_SIGNUP_EMAIL = 'SET_SIGNUP_EMAIL'
export const SET_SIGNUP_PASSWORD = 'SET_SIGNUP_PASSWORD'
export const SET_SIGNUP_REPASSWORD = 'SET_SIGNUP_REPASSWORD'

export const SET_VERTIFY_EMAIL = 'SET_VERTIFY_EMAIL'




//LOGIN

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const SET_LOGIN_WALLETID = 'SET_LOGIN_WALLETID'
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD'

//HOME

export const SHOW_ALL_TRANSACTIONS = 'SHOW_ALL_TRANSACTIONS'
export const SHOW_ALL_TRANSACTIONS_SUCCESS = 'SHOW_ALL_TRANSACTIONS_SUCCESS'
export const SHOW_ALL_TRANSACTIONS_FAILURE = 'SHOW_ALL_TRANSACTIONS_FAILURE'

//DASHBOARD

export const SET_DASHBOARD_TO = 'SET_DASHBOARD_TO'
export const SET_DASHBOARD_AMOUNT = 'SET_DASHBOARD_AMOUNT'
export const SHOW_ALL_TRANSACTIONS_RECEIVE = 'SHOW_ALL_TRANSACTIONS_RECEIVE'
export const SHOW_ALL_TRANSACTIONS_RECEIVE_SUCCESS = 'SHOW_ALL_TRANSACTIONS_RECEIVE_SUCCESS'
export const SHOW_ALL_TRANSACTIONS_RECEIVE_FAILURE = 'SHOW_ALL_TRANSACTIONS_RECEIVE_FAILURE'
export const SHOW_ALL_TRANSACTIONS_SEND = 'SHOW_ALL_TRANSACTIONS_SEND'
export const SHOW_ALL_TRANSACTIONS_SEND_SUCCESS = 'SHOW_ALL_TRANSACTIONS_SEND_SUCCESS'
export const SHOW_ALL_TRANSACTIONS_SEND_FAILURE = 'SHOW_ALL_TRANSACTIONS_SEND_FAILURE'
export const SEND_MONEY = 'SEND_MONEY'
export const SEND_MONEY_SUCCESS = 'SEND_MONEY_SUCCESS'
export const SEND_MONEY_FAILURE = 'SEND_MONEY_FAILURE'